[project]
name = "meal_mcp"
version = "0.1.0"
description = "Manage meal planning and pantry management using an LLM for business logic"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.1.1",
    "dash-bootstrap-components>=2.0.3",
    "mcp[cli]>=1.12.2",
    "pytest>=8.4.1",
]
